name: gforth # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.7.9-20190404' # just for humans, typically '1.2+git' or '1.3.2'
summary: gforth snap # 79 char long summary
description: |
  This is gforth snap

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  gforth:
    command: bin/gforth

parts:
  gforth:
    source: https://www.complang.tuwien.ac.at/forth/gforth/Snapshots/0.7.9_20190404/gforth-0.7.9_20190404.tar.xz
    plugin: autotools
    build-packages:
      - libtool-bin
