name: gforth-forthy # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.7.9-20200213' # just for humans, typically '1.2+git' or '1.3.2'
summary: gforth snap # 79 char long summary
description: |
  This is gforth snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+ # SPDX 2.0 identifiers

apps:
  gforth:
    command: bin/gforth
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth-forthy/current/lib/gforth/0.7.9_20200213/amd64/libcc-named
    plugs:
      - home
      - network
      - x11
      - opengl
  gforth-fast:
    command: bin/gforth-fast
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth-forthy/current/lib/gforth/0.7.9_20200213/amd64/libcc-named
    plugs:
      - home
      - network
      - x11
      - opengl
  gforth-itc:
    command: bin/gforth-itc
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth-forthy/current/lib/gforth/0.7.9_20200213/amd64/libcc-named
    plugs:
      - home
      - network
      - x11
      - opengl
  gforth-ditc:
    command: bin/gforth-ditc
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth-forthy/current/lib/gforth/0.7.9_20200213/amd64/libcc-named
    plugs:
      - home
      - network
      - x11
      - opengl

parts:
  gforth:
#    source: https://www.complang.tuwien.ac.at/forth/gforth/Snapshots/0.7.9_20200213/gforth-0.7.9_20200213.tar.xz
    source: https://net2o.de/gforth/gforth-0.7.9_20200213_5.tar.xz
    plugin: autotools
    configflags:
      - --with-install=swig,freetype-gl
      - --disable-lib
    build-packages:
      - libtool-bin
      - libltdl-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxrandr-dev
      - libgles2-mesa-dev
      - libgl1-mesa-dev
      - libwayland-dev
      - libvulkan-dev
      - libpng-dev
      - libfreetype6-dev
      - libffi-dev
      - texinfo
      - git
      - g++
      - premake4
      - yodl
      - bison
      - libpcre3-dev
      - libboost-dev
    stage-packages:
      - libltdl7
      - libegl1
      - libfreetype6
      - libgl1
      - libgles2
      - libglvnd0
      - libglx0
      - libpng16-16
      - libvulkan1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrandr2
      - libxrender1
