name: gforth-forthy # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.7.9-20200213' # just for humans, typically '1.2+git' or '1.3.2'
summary: gforth snap # 79 char long summary
description: |
  This is gforth snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+ # SPDX 2.0 identifiers

apps:
  gforth:
    command: bin/gforth
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
    plugs:
      - home
      - network
      - x11
      - opengl
  gforth-fast:
    command: bin/gforth-fast
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
    plugs:
      - home
      - network
      - x11
      - opengl
  gforth-itc:
    command: bin/gforth-itc
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
    plugs:
      - home
      - network
      - x11
      - opengl
  gforth-ditc:
    command: bin/gforth-ditc
    environment:
      GFORTHPATH: .:/snap/gforth-forthy/current/lib/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/0.7.9_20200213:/snap/gforth-forthy/current/share/gforth/site-forth:~+
    plugs: 
      - home
      - network
      - x11
      - opengl

parts:
  gforth:
    source: https://www.complang.tuwien.ac.at/forth/gforth/Snapshots/0.7.9_20200213/gforth-0.7.9_20200213.tar.xz
    plugin: autotools
    build-packages:
      - libtool-bin
      - libltdl-dev
    stage-packages:
      - libltdl7
