name: gforth # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.7.9-20200410' # just for humans, typically '1.2+git' or '1.3.2'
summary: gforth snap # 79 char long summary
description: |
  This is the weekly development snapshot of Gforth in snap format. Building
  for snap has made considerable progress, all SWIG-generated libraries load,
  OpenGL via GLX works.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
type: app
license: GPL-3.0+ # SPDX 2.0 identifiers

apps:
  gforth:
    command: bin/gforth
    environment:
      GFORTHPATH: .:/snap/gforth/current/lib/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth/current/lib/gforth/0.7.9_20200410/amd64/libcc-named
      GFORTHFONTS: /snap/gforth/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/gforth/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
      LOCPATH: /snap/gforth/current/usr/lib/locale
    plugs:
      - home
      - network
      - x11
      - opengl
      - unity7
      - locale-control
  gforth-fast:
    command: bin/gforth-fast
    environment:
      GFORTHPATH: .:/snap/gforth/current/lib/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth/current/lib/gforth/0.7.9_20200410/amd64/libcc-named
      GFORTHFONTS: /snap/gforth/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/gforth/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
      LOCPATH: /snap/gforth/current/usr/lib/locale
    plugs:
      - home
      - network
      - x11
      - opengl
      - unity7
      - locale-control
  gforth-itc:
    command: bin/gforth-itc
    environment:
      GFORTHPATH: .:/snap/gforth/current/lib/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth/current/lib/gforth/0.7.9_20200410/amd64/libcc-named
      GFORTHFONTS: /snap/gforth/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/gforth/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
      LOCPATH: /snap/gforth/current/usr/lib/locale
    plugs:
      - home
      - network
      - x11
      - opengl
      - unity7
      - locale-control
  gforth-ditc:
    command: bin/gforth-ditc
    environment:
      GFORTHPATH: .:/snap/gforth/current/lib/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/0.7.9_20200410:/snap/gforth/current/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/gforth/current/lib/gforth/0.7.9_20200410/amd64/libcc-named
      GFORTHFONTS: /snap/gforth/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/gforth/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
      LOCPATH: /snap/gforth/current/usr/lib/locale
    plugs:
      - home
      - network
      - x11
      - opengl
      - unity7
      - locale-control

parts:
  prepare:
    plugin: nil
    override-pull: |
      echo "deb [arch=i386,amd64,armhf,armel,arm64,powerpc,mips,mipsel,all] https://net2o.de/debian testing main" >/etc/apt/sources.list.d/net2o.list
      wget -O - https://net2o.de/bernd@net2o.de-yubikey.pgp.asc | apt-key add -
      apt update
    prime: [-*]
    build-packages:
      - software-properties-common
      - dirmngr
  desktop-glib-only:
    source: .
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
      - locales-all
      - locales
  gforth:
    after:
       - prepare
       - desktop-glib-only
    source: https://www.complang.tuwien.ac.at/forth/gforth/Snapshots/0.7.9_20200410/gforth-0.7.9_20200410.tar.xz
#    source: https://net2o.de/gforth/gforth-0.7.9_20200410.tar.xz
    plugin: autotools
    configflags:
      - --with-install=swig
      - --disable-lib
    build-packages:
      - libtool-bin
      - libltdl-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxrandr-dev
      - libgles2-mesa-dev
      - libgl1-mesa-dev
      - libwayland-dev
      - libvulkan-dev
      - libpng-dev
      - libfreetype6-dev
      - libffi-dev
      - libgps-dev
      - texinfo
      - git
      - g++
      - yodl
      - bison
      - libpcre3-dev
      - libboost-dev
      - libsoil2
      - freetype-gl
    stage-packages:
      - locales-all
      - locales
      - libltdl7
      - libfreetype6
      - libglvnd0
      - libglx0
      - libpng16-16
      - libvulkan1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libegl1-mesa
      - libgles2-mesa
      - libgl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrandr2
      - libxrender1
      - fonts-noto
      - fonts-liberation
      - libsoil2
      - freetype-gl
      - fonts-noto-emoji
      - fonts-awesome
